### ISSUE TITLE
大佬好久没看资料了这个 mtwifi-cfg 是什么

### ISSUE THREAD

**Issue by lalasou** [lgs2007m/Actions-OpenWrt#1]
今天看更新不少东西 准备编译  发现多了个配置
大佬好久没看资料了这个 mtwifi-cfg 是什么

**Comment by lgs2007m** [comment]
带mtwifi的是hanwckf做的无线luci界面，比较简洁；不带的是原厂sdk的无线界面。
可以看大佬博客的介绍https://cmi.hanwckf.top/p/immortalwrt-mt798x/

**Comment by lalasou** [comment]
> 带mtwifi的是hanwckf做的无线luci界面，比较简洁；不带的是原厂sdk的无线界面。
> 
> 可以看大佬博客的介绍https://cmi.hanwckf.top/p/immortalwrt-mt798x/

好的  谢谢大佬

**Comment by lalasou** [comment]
> 带mtwifi的是hanwckf做的无线luci界面，比较简洁；不带的是原厂sdk的无线界面。
> 
> 可以看大佬博客的介绍https://cmi.hanwckf.top/p/immortalwrt-mt798x/

哪个更好用啊 大佬
