### ISSUE TITLE
ax1800 pro大分区的gpt文件64G和128G两种通用吗

### ISSUE THREAD

**Issue by hdstar2009** [lgs2007m/Actions-OpenWrt#10]
请教如题。找了不少文章似乎都没明确64G版和128G版是否通用这个gpt文件。

**Comment by lgs2007m** [comment]
我的教程中已经说明，只有gpt分区表中扇区总数数小于eMMC实际扇区数，才可以。自行理解吧，不做科普指导。
我改的gpt分区表因为没有最后一个storage分区，所以64G、128G、256G通刷，刷好之后再新建storage分区即可。
其他人改的自行甄别，可以使用[gpt_parser_to_xml.py](https://github.com/lu-1991/cdt-gpt-ipq60xx-generate/blob/master/meta-tools/scripts/gpt_parser_to_xml.py)解析分区表，查看里面的分区及扇区总数。
