### ISSUE TITLE
百里固件CPU显示BUG

### ISSUE THREAD

**Issue by bwnqx** [lgs2007m/Actions-OpenWrt#13]
猫大您好，百里固件在关闭WiFi之后，luci上cpu会一直显示有20+的占用，top查看实际无占用。开启无线后正常。
![d5fcaed86603008adaedaf96e5f19331](https://github.com/lgs2007m/Actions-OpenWrt/assets/51857207/a5cc1ffe-053c-4c4d-b52c-b6ef83cf8714)

**Comment by bwnqx** [comment]
好嘞，我直接编译个nowifi的试试

**Comment by ALILEX-1** [comment]
> 好嘞，我直接编译个nowifi的试试

编译完怎么样呢

**Comment by bwnqx** [comment]
> > 好嘞，我直接编译个nowifi的试试
> 
> 编译完怎么样呢

编译后正常的，应该是某个插件的问题。我自己编译后有WIFI和无WIFI都正常

**Comment by ALILEX-1** [comment]
貌似是wan3插件造成的，卸载后恢复正常
