### ISSUE TITLE
是否可以刷入Lean大的QWRT闭源固件？

### ISSUE THREAD

**Issue by peplemon** [lgs2007m/Actions-OpenWrt#15]
猫大，感谢您的详细教程，我已成功刷入uboot，并刷入了您制作的0405固件。
在看其他人的问题时，发现您有个回复这么说 “用闭源固件或者原厂固件，就用我的教程。你要用OpenWrt主线或者Immortalwrt的固件，得按他们的教程重新刷一遍机子了。我没试过，自行尝试吧。”
请问使用您的uboot能否直接刷入恩山上lean大的“潘多拉 QWRT for MT7986 京东云 百里 2.5G有线 AX6000 R23.12.12 闭源固件”呢？
感谢！

**Comment by lgs2007m** [comment]
可以的，QWRT也是闭源的，教程里面第一段就说了。
