### ISSUE TITLE
可以将源替换成https://github.com/openwrt/openwrt吗？我替换后编译openwrt-23.05失败了

### ISSUE THREAD

**Issue by itq5** [lgs2007m/Actions-OpenWrt#16]
可以将源替换成https://github.com/openwrt/openwrt吗？我替换后编译openwrt-23.05失败了

0s
Run [ -e $CONFIG_FILE ] && mv $CONFIG_FILE openwrt/.config
  [ -e $CONFIG_FILE ] && mv $CONFIG_FILE openwrt/.config
  chmod +x $DIY_P2_SH
  cd openwrt
  $GITHUB_WORKSPACE/$DIY_P2_SH
  shell: /usr/bin/bash -e {0}
  env:
    OPENWRT_NAME: hanwckf
    REPO_URL: https://github.com/openwrt/openwrt
    REPO_BRANCH: openwrt-23.05
    FEEDS_CONF: feeds.conf.default
    CONFIG_FILE: JDCloud-AX6000-Baili/.mtwifi-cfg.config
    DIY_P[1](https://github.com/itq5/Actions-OpenWrt/actions/runs/9379714546/job/25825205320#step:8:1)_SH: JDCloud-AX6000-Baili/diy-part1.sh
    DIY_P2_SH: JDCloud-AX6000-Baili/diy-part[2](https://github.com/itq5/Actions-OpenWrt/actions/runs/9379714546/job/25825205320#step:8:2).sh
    SSH_ACTIONS: false
    UPLOAD_FIRMWARE: true
    UPLOAD_RELEASE: true
    TZ: Asia/Shanghai
sed: can't read package/emortal/autocore/files/generic/cpuinfo: No such file or directory
Error: Process completed with exit code 2.

**Comment by lgs2007m** [comment]
我只用闭源驱动的，OpenWrt和ImmortalWrt主线都是开源的，不一样，不能套用我这个Action，固件也不能通刷。
如果要用开源固件，去看看开源固件的编译和刷机教程吧。
