### ISSUE TITLE
JDCloud-AX6000-Baili能把内核换到6.6吗以及预装iStore

### ISSUE THREAD

**Issue by itq5** [lgs2007m/Actions-OpenWrt#17]
JDCloud-AX6000-Baili能把内核换到6.6吗以及预装iStore

**Comment by lgs2007m** [comment]
6.6是开源的吧，我不用开源的，你可以去看看开源的刷机教程。
iStore对我来说没啥用，你需要的话自己添加插件吧

**Comment by lgs2007m** [comment]
更换uboot和gpt可以同时支持21.02闭源固件和openwrt、immortalwrt主线master/23.05分支固件了，可以自己编译6.6内核固件
https://github.com/lgs2007m/Actions-OpenWrt/releases/tag/2024.09.16-2149-immortalwrt-mainline-support
