### ISSUE TITLE
几个问题

### ISSUE THREAD

**Issue by peplemon** [lgs2007m/Actions-OpenWrt#18]
猫大，刷了0405版固件（2024.04.05-1907-hanwckf-jdcloud_re-cp-03-mtwifi-docker-squashfs-sysupgrade）
问题1：静态ip模式联网，开启wifi，什么插件都没开，只连了 一个终端，cpu占用在0-20之间波动，其中占用20+的时间还挺长，这种情况正常吗？需要重刷吗？
![cpu占用](https://github.com/lgs2007m/Actions-OpenWrt/assets/12671740/95355e3a-b0eb-4cb1-b37a-7bbd6ce0886e)

问题2: 通过  系统-软件包-在线安装的方式，检索到的插件不是最新版（和我N1的openwrt对比），ssrplus插件安装成功后里面没有navie等协议，还有mosdns检索到的也不是最新版。能不能将N1的发行版软件源（openwrt）复制粘贴到immortalwrt里面实现更新和安装呢？

感谢猫大

**Comment by lgs2007m** [comment]
我这个固件插件是有点多的，不知有没有影响。我自己是跑了一些插件和docker，没跑科学，cpu占用20-30%这样，你可以ssh或ttyd查看使用htop命令看看资源占用。我觉得这个是正常的，重刷不会降低占用的，不用重刷。你也可以试试其他人编译的[闭源固件](https://github.com/VIKINGYFY/CloseWRT-CI/releases)看看或者QWRT。

hanwckf大佬闭源仓库是ImmortalWrt 21.02 内核5.4，使用的软件对应的是ImmortalWrt的[openwrt-21.02分支](https://github.com/immortalwrt/luci/tree/openwrt-21.02)，这个分支天灵大佬许久没更新了，所以不是最新的了。
除非有问题，不用追最新的插件。更改不是21.02分支的软件源可能不行，可能得关闭option check_signature，而且关闭也不知道能不能用……你可以尝试下。
