### ISSUE TITLE
docker拉取镜像失败

### ISSUE THREAD

**Issue by hereVg0** [lgs2007m/Actions-OpenWrt#19]
大佬好，我刷了你的百里固件
[2024.05.13-1807-hanwckf-jdcloud_re-cp-03-gsw-mtwifi-docker]，
在使用docker拉取镜像的时候总是失败。提示为：
422ed46b1a92: Retrying in 10 seconds 
a570a7a2bb41: Retrying in 1 second 
docker: error pulling image configuration: download failed after attempts=6: net/http: TLS handshake timeout.
我尝试了魔法，全局魔法，搜索的上网的教程，更换国内源的地址；我也重新再刷了一次固件，但是问题依然没有解决。请问是哪里出错了吗？

**Comment by lgs2007m** [comment]
拉取镜像的确很慢，这个是网络环境问题。
我之前看到一个方法是先停止WAN6接口，就是先暂停IPv6，这样拉取会顺畅许多。
