### ISSUE TITLE
这个是干嘛的CONFIG_TARGET_PER_DEVICE_ROOTFS=y 我看默认会有

### ISSUE THREAD

**Issue by lalasou** [lgs2007m/Actions-OpenWrt#2]
这个是干嘛的CONFIG_TARGET_PER_DEVICE_ROOTFS=y 我看默认会有

**Comment by lgs2007m** [comment]
具体我也不懂，就是编译多个机型需要选上，你直接问ChatGPT即可。
我自用的云编译，有bug可以反映，太懒了不做解答……
