### ISSUE TITLE
大佬，刷了雅典娜的uboot和大分区，才发现好像没有OP的固件

### ISSUE THREAD

**Issue by kidxiang** [lgs2007m/Actions-OpenWrt#26]
找了一圈都没找到，是不是现在网上还没有啊？
我是不是只有刷回原厂？

**Comment by lgs2007m** [comment]
只有lean大雕的VIP中的VIP，即SVIP群才有固件。或者你上咸鱼看看
你没有固件只能先刷原厂继续用，因为我的教程uboot、分区都是支持原厂的。

**Comment by lgs2007m** [comment]
lean大佬开源亚瑟、雅典娜了，可以去看看 https://github.com/coolsnowwolf/lede

**Comment by rbzan** [comment]
老哥，能帮忙给个mmcblk0p26_swap.bin文件不，备份的时候少复制了一行
