### ISSUE TITLE
请教一下，百里编译文件diy-part2里面，设置CPU频率的语句作用是什么呢？

### ISSUE THREAD

**Issue by shiocc** [lgs2007m/Actions-OpenWrt#29]
文件里对CPU频率进行了手动设定：sed -i '/"mediatek"\/\*|\"mvebu"\/\*/{n; s/.*/\tcpu_freq="2.0GHz" ;;/}' package/emortal/autocore/files/generic/cpuinfo
这里作用是什么呢？我害怕会让CPU保持2GHz运行，消耗更多电量

**Comment by lgs2007m** [comment]
mt798x是定频运行，不能调整频率，这个只是个人喜好，把频率固定显示出来
