### ISSUE TITLE
wifi日志问题

### ISSUE THREAD

**Issue by qiaoliG** [lgs2007m/Actions-OpenWrt#3]
冒昧请教大佬，百里路由器系统日志里全部是wifi的内容，几分钟刷一遍。有什么办法处理吗？

Tue May 21 16:43:42 2024 kern.warn kernel: [78730.320078] 7986@C01L2,wifi_sys_disconn_act() 1002:  wdev_idx=0
Tue May 21 16:43:42 2024 kern.notice kernel: [78730.326812] 7986@C08L3,hw_ctrl_flow_v2_disconnt_act() 172: wdev_idx=0
Tue May 21 16:43:42 2024 kern.warn kernel: [78730.333999] 7986@C13L2,MacTableDeleteEntry() 1793: Del Sta:
Tue May 21 16:43:42 2024 kern.notice kernel: [78730.341430] 7986@C08L3,ap_peer_deauth_action() 429: AUTH - receive DE-AUTH(seq-885) from 78:df:, reason=3
Tue May 21 16:43:54 2024 kern.notice kernel: [78742.818239] 7986@C08L3,ap_peer_auth_req_at_idle_action() 717: AUTH - MBSS(0), Rcv AUTH seq#1, Alg=0, Status=0 from [wcid=1023]
Tue May 21 16:43:54 2024 kern.debug kernel: [78742.831160] entrytb_aid_aquire(): found non-occupied aid:3, allocated from:2
Tue May 21 16:43:54 2024 kern.warn kernel: [78742.831173] 7986@C13L2,MacTableInsertEntry() 1537: New Sta:78:df:
Tue May 21 16:43:54 2024 kern.notice kernel: [78742.842537] 7986@C08L3,ap_cmm_peer_assoc_req_action() 1647:  Recv Assoc from STA - 78:df
Tue May 21 16:43:54 2024 kern.notice kernel: [78742.851966] 7986@C08L3,ap_cmm_peer_assoc_req_action() 2170: ASSOC Send ASSOC response (Status=0)...
Tue May 21 16:43:54 2024 kern.notice kernel: [78742.861131] 7986@C01L3,wifi_sys_conn_act() 1115: wdev idx = 0
Tue May 21 16:43:54 2024 kern.notice kernel: [78742.867588] 7986@C08L3,hw_ctrl_flow_v2_connt_act() 215: wdev_idx=0
Tue May 21 16:43:54 2024 kern.notice kernel: [78742.998432] 7986@C15L3,WPABuildPairMsg1() 5278: <=== send Msg1 of 4-way
Tue May 21 16:43:54 2024 kern.notice kernel: [78743.009557] 7986@C15L3,PeerPairMsg2Action() 6197: ===>Receive msg 2
Tue May 21 16:43:54 2024 kern.notice kernel: [78743.016323] 7986@C15L3,WPABuildPairMsg3() 5555: <=== send Msg3 of 4-way
Tue May 21 16:43:54 2024 kern.notice kernel: [78743.024508] 7986@C15L3,PeerPairMsg4Action() 6627: ===>Receive msg 4
Tue May 21 16:43:54 2024 kern.warn kernel: [78743.036180] 7986@C15L2,PeerPairMsg4Action() 6989: AP SETKEYS DONE(ra0) - AKMMap=WPA2PSK, PairwiseCipher=AES, GroupCipher=AES, wcid=2 from 78:df:
Tue May 21 16:43:54 2024 kern.warn kernel: [78743.036180]

**Comment by lgs2007m** [comment]
不懂，使用正常不用管
