### ISSUE TITLE
有个问题 想问一下 AX1800pro 这个系统的dtb能上1G的 RAM吗

### ISSUE THREAD

**Issue by rodren-lion** [lgs2007m/Actions-OpenWrt#36]
有个问题 想问一下 AX1800pro 这个系统的dtb能上1G的 RAM吗 
主要还没刷.. 准备有空刷一下 还有一批 矿渣 改了做路由算了.... 原版512 上OP 似乎有点小.....

**Comment by magisk317** [comment]
有那么一瞬间，我竟然在想你说的是512是M还是G，哈哈哈，因为我的是256G的

**Comment by lgs2007m** [comment]
> 有个问题 想问一下 AX1800pro 这个系统的dtb能上1G的 RAM吗 主要还没刷.. 准备有空刷一下 还有一批 矿渣 改了做路由算了.... 原版512 上OP 似乎有点小.....

dtb上1G？NSS用1G Profile的意思吗？
原厂就512M不建议开，要内存只需硬改1G即可。
大雕说雅典娜的NSS是用1G Profile。

**Comment by rodren-lion** [comment]
> 有那么一瞬间，我竟然在想你说的是512是M还是G，哈哈哈，因为我的是256G的

不好意思让你误解了，。是RAM 512M
准备换1G
