### ISSUE TITLE
 老哥，能帮忙给个mmcblk0p26_swap.bin文件不，备份的时候少复制了一行

### ISSUE THREAD

**Issue by rbzan** [lgs2007m/Actions-OpenWrt#43]
现在导致我卡在这一步，不能恢复分区跑分了。

WinSCP之类软件上传下面3个备份文件到/mnt/mmcblk0p27
mmcblk0p24_log.bin
mmcblk0p25_plugin.bin
mmcblk0p26_swap.bin

使用下面命令刷回：

dd if=/dev/zero of=$(blkid -t PARTLABEL=0:ETHPHYFW -o device) conv=fsync
dd if=/mnt/mmcblk0p27/mmcblk0p24_plugin.bin of=$(blkid -t PARTLABEL=plugin -o device) conv=fsync
dd if=/mnt/mmcblk0p27/mmcblk0p25_log.bin of=$(blkid -t PARTLABEL=log -o device) conv=fsync
swapoff $(blkid -t PARTLABEL=swap -o device)
dd if=/mnt/mmcblk0p27/mmcblk0p26_swap.bin of=$(blkid -t PARTLABEL=swap -o device) conv=fsync
swapon $(blkid -t PARTLABEL=swap -o device)
第1个命令如果swap分区已经卸载，会报错，这是正常的，不用管：failed to swapoff /dev/mmcblk0p26 (-1)
第2个命令dd像mmcblk0p23没有空间，这是正常的，不用管：error writing '/dev/mmcblk0p23': No space left on device
其他几个个命令没有报错即可。

**Comment by lgs2007m** [comment]
理论上不需要，自己新建swap分区即可。
我没试过，自己试试吧。恩山有很多分享的，自己找
