### ISSUE TITLE
docker需要单独安装吗？

### ISSUE THREAD

**Issue by gqm36524** [lgs2007m/Actions-OpenWrt#45]
我更新到2024.07.15-1510-hanwckf-jdcloud_re-cp-03-gsw-mtwifi-docker-squashfs-sysupgrade.bin，docker页面就成这样了。
如图：
![QQ_1721823519046](https://github.com/user-attachments/assets/a886bef0-1266-4e93-a616-a3fb6155c8d2)

**Comment by gqm36524** [comment]
容器 镜像啥的选项没有了

**Comment by bwnqx** [comment]
> 容器 镜像啥的选项没有了

重启路由器就好了

**Comment by gqm36524** [comment]
找到原因了，我安装了istore里的蓝山云。卸载掉就正常了QAQ
