### ISSUE TITLE
京东云百里固件是否完整支持kvr协议无缝漫游？

### ISSUE THREAD

**Issue by yushu280** [lgs2007m/Actions-OpenWrt#47]
谢谢大佬的7.15固件，用起来很舒服，就是有个美中不足之处，无线网络设置中只看到k，没看到v和r。那么，到底支不支持v和r？是否完整支持kvr协议无缝漫游？

**Comment by lgs2007m** [comment]
hanwckf大佬闭源支持k v，v默认开启，还不支持r。你可以试试大雕的QWRT

**Comment by lgs2007m** [comment]
对了，237大佬的仓库源码添加了r的支持，可以自己编译看看
https://github.com/padavanonly/immortalwrt-mt798x

**Comment by Narut0123** [comment]
> 对了，237大佬的仓库源码添加了r的支持，可以自己编译看看 https://github.com/padavanonly/immortalwrt-mt798x

加菲大佬大概啥时更新百里的固件啊？

**Comment by lgs2007m** [comment]
> > 对了，237大佬的仓库源码添加了r的支持，可以自己编译看看 https://github.com/padavanonly/immortalwrt-mt798x
> 
> 加菲大佬大概啥时更新百里的固件啊？

不更啦，追新可以用237大佬的源码编译

**Comment by Narut0123** [comment]
> > > 对了，237大佬的仓库源码添加了r的支持，可以自己编译看看 https://github.com/padavanonly/immortalwrt-mt798x
> > 
> > 
> > 加菲大佬大概啥时更新百里的固件啊？
> 
> 21.02万年不变了，不更啦，追新可以用237大佬的源码编译，他还有一些功能性更新

啊这！好吧

**Comment by lgs2007m** [comment]
新编译的固件应该是支持kvr了，你可以试试，我不懂不测试了
https://github.com/lgs2007m/Actions-OpenWrt/releases/tag/2024.08.29-1258-hanwckf-jdcloud_re-cp-03-gsw-mtwifi-docker
