### ISSUE TITLE
请教关于RE-CP-03的官方23.05固件

### ISSUE THREAD

**Issue by maximaas** [lgs2007m/Actions-OpenWrt#5]
大神你好，感谢这个非常棒的教程，我已经按照步骤刷好了我的百里64G。

想请问一下在此基础之上如果要刷入openwrt或immortalwrt的RE-CP-03的23.05.2固件应该如何操作？

谢谢，期待回复。

**Comment by lgs2007m** [comment]
用闭源固件或者原厂固件，就用我教程。你要用OpenWrt主线或者Immortalwrt的固件，得按他们的教程重新刷一遍机子了。我没试过，自行尝试吧。
