### ISSUE TITLE
百里新的交换机驱动有什么不同吗？

### ISSUE THREAD

**Issue by AzulEterno** [lgs2007m/Actions-OpenWrt#53]
我注意到别的mt7986机型一般有个虚拟交换机页面进行管理，目前现在百里没有。换了驱动后有什么不同吗？要不要重新merge到百里的profile里面？

**Comment by lgs2007m** [comment]
看[Readme.md](https://github.com/lgs2007m/Actions-OpenWrt/blob/main/Readme.md)

**Comment by lgs2007m** [comment]
> 我改了使用GSW的dts，但是网络的页面里面依然没有出现交换机。。。

看我的自己检查[02_network](https://github.com/lgs2007m/Actions-OpenWrt/blob/main/.github/workflows/JDCloud-AX6000-Baili-hanwckf.yml#L158)配置，不做指导
