### ISSUE TITLE
京东云亚瑟的固件还更新吗？

### ISSUE THREAD

**Issue by wangwen6666** [lgs2007m/Actions-OpenWrt#54]
2024.05.23-1737-JiaY-shi-jdc_ax1800-pro-docker-squashfs-factory

看最新的一版说USB有问题。再上一版就是我刚才发的这个名称。请问2024.05.23这个还可以用吗，有什么严重的问题吗？

**Comment by lgs2007m** [comment]
不建议使用，使用其他仓库编译的吧，好像已经解决USB问题。
我没有亚瑟、雅典娜路由器设备，不更新了

**Comment by wangwen6666** [comment]
有推荐的吗，大佬

**Comment by lgs2007m** [comment]
> 有推荐的吗，大佬

没有。我只用过QWRT和我自己编译的，要推荐就推荐QWRT咯
