### ISSUE TITLE
大佬，关于雅典娜刷机问题

### ISSUE THREAD

**Issue by xupeixuan** [lgs2007m/Actions-OpenWrt#57]
第一次尝试刷机，在成功进入uboot页面后将`uboot-JDC_AX1800_Pro-AX6600_Athena-20240510.bin`文件刷入，重启后尝试刷入`JDCOS-JDC02-1.5.40.r2181-b0c0abcc9cac06813d0d1689feb6f052-signed.img`失败，错误信息为 
![image](https://github.com/user-attachments/assets/9b9c02dd-c90d-4fff-9dfc-25af9c71cec3)

在此基础上，我查看文档说刷机顺序为 先刷UBOOT-刷入分区表-刷入底层固件. 因此后先后尝试刷入分区表和cdt文件，但是依然无法成功启动系统。

我理解正确的步骤应该是进入uboot，然后刷入低版本的固件，再开启ssh。只是我当前这种错误是哪一步造成的，应该怎么补救？
大佬时间宝贵可以有偿解决问题 0.0

**Comment by xupeixuan** [comment]
刷机方式为9008模式直接刷uboot

**Comment by lgs2007m** [comment]
先9008刷uboot，再刷固件，正确的。
刷完uboot后可以正常进uboot吗？（不是9008进uboot）如果可以，说明已刷uboot成功。
刷原厂img固件失败，这个按理说不可能，我也不懂，你有TTL自己看下错误代码

**Comment by xupeixuan** [comment]
现在可以通过长按reset进入uboot，但是想要降级固件失败，那我在研究研究，谢谢大佬

**Comment by lgs2007m** [comment]
> 现在可以通过长按reset进入uboot，但是想要降级固件失败，那我在研究研究，谢谢大佬

下载我仓库里面的，注意解压后再使用。刷原厂固件，不需要刷gpt分区表，不需要刷内存cdt。
实在不行，再刷下gpt分区表，cdt是改内存才刷的

**Comment by xupeixuan** [comment]
感谢大佬，已经成功了。谢谢
