### ISSUE TITLE
大佬 改功率改错了  然后无线连不上了

### ISSUE THREAD

**Issue by lalasou** [lgs2007m/Actions-OpenWrt#58]
硬改的分区

这种情况  是回原厂然后 刷uboot 再来一遍还是怎么搞  

😓

**Comment by lgs2007m** [comment]
有线连接，把备份的factory分区刷回去并替换MT7986_ePAeLNA_EEPROM_AX6000.bin，然后重启
```
dd if=/tmp/mmcblk0p3_factory.bin of=$(blkid -t PARTLABEL=factory -o device) conv=fsync
dd if=/tmp/mmcblk0p3_factory.bin of=/lib/firmware/MT7986_ePAeLNA_EEPROM_AX6000.bin
```

**Comment by lalasou** [comment]
> 有线连接，把备份的factory分区刷回去并替换MT7986_ePAeLNA_EEPROM_AX6000.bin，然后重启
> 
> ```
> 
> dd if=/tmp/mmcblk0p3_factory.bin of=$(blkid -t PARTLABEL=factory -o device) conv=fsync
> 
> dd if=/tmp/mmcblk0p3_factory.bin of=/lib/firmware/MT7986_ePAeLNA_EEPROM_AX6000.bin
> 
> ```

收到   谢谢大佬
