### ISSUE TITLE
京东百里AX6000更新2024.10.16-0916版固件后出现已安装软件消失且更新软件包列表出错

### ISSUE THREAD

**Issue by fya16838** [lgs2007m/Actions-OpenWrt#64]
作者你好，我在下载最新构建的2024.10.16-0916-hanwckf-jdcloud_re-cp-03-v7672-gsw-docker固件后出现原本安装的软件消失，且无法更新软件包列表，这是什么原因呢？用的系统的更新功能，不是U-BOOT更新的。是不是每次更新都无法保留已安装软件和配置。如果可以的话该如何操作呢？能否解答一下，万分感谢！

![微信截图_20241017225042](https://github.com/user-attachments/assets/78c5bb56-0498-4e40-84df-6632dcdc9c4c)
![image](https://github.com/user-attachments/assets/de5be07a-81b2-4eb5-8e5a-74ed030509d4)

**Comment by lgs2007m** [comment]
不是操作问题，系统中更新固件不会保留之前安装的插件，最多保留之前的配置，这是基础知识。
我使用的是相同固件，更新软件包列表没有问题，检查自己网络。

**Comment by fya16838** [comment]
感谢解答，因为我需要一些插件，我在想可不可以自己构建，所以我Fork了你的代码，请问下增加新的软件包是不是如下图位置，格式为：CONFIG_PACKAGE_软件包名称=y
![image](https://github.com/user-attachments/assets/8dc47e4d-4814-4828-835d-ed5427aa7b12)

**Comment by lgs2007m** [comment]
是的，添加的插件需要[feeds.conf.default](https://github.com/lgs2007m/Actions-OpenWrt/blob/main/JDCloud-AX6000-Baili-hanwckf/feeds.conf.default)软件源当中的，如果软件源没有，需要修改[diy-part1.sh](https://github.com/lgs2007m/Actions-OpenWrt/blob/main/JDCloud-AX6000-Baili-hanwckf/diy-part1.sh)添加源码，再添加CONFIG_PACKAGE

**Comment by lgs2007m** [comment]
自己搜索学习，不做教学

**Comment by fya16838** [comment]
好的
