### ISSUE TITLE
猫佬好，刷机教程不见了

### ISSUE THREAD

**Issue by 673271913** [lgs2007m/Actions-OpenWrt#65]
据说猫佬的教程最能学到东西，这两天打开都是显示删除。如若因无奈需要删除，就太可惜了。

**Comment by lgs2007m** [comment]
没有删除，换地方了。看教程直接看https://github.com/lgs2007m/Actions-OpenWrt/tree/main/Tutorial
或者直接下载教程文件压缩包，里面也有文字教程了https://github.com/lgs2007m/Actions-OpenWrt/releases/tag/Router-Flashing-Files
