### ISSUE TITLE
求问，网络共享 功能你们能正常用吗？

### ISSUE THREAD

**Issue by funnystyle1991** [lgs2007m/Actions-OpenWrt#67]
我折腾一天了 网上查的都试了，都不能用，一直提示密码错误，安卓和windows都这样，电脑smb1什么的都设置了，换成 大雕的固件 却能用，不过大雕用的好像是samb3。
所以，想求证下 是固件问题 还是我 自己的问题？

**Comment by lgs2007m** [comment]
我不设置密码，开启强制Root，可以正常访问。
可能插件有点问题吧，不行就换其他的

**Comment by funnystyle1991** [comment]
心累，各种折腾，终于好了，换成samba3就行了，可以用华为手机的备份功能了
