### ISSUE TITLE
JDCloud-AX6000关于备份原厂分区mmcblk0

### ISSUE THREAD

**Issue by ghwrf** [lgs2007m/Actions-OpenWrt#68]
dd if=/dev/mmcblk0 bs=512 skip=34 count=8158 of=/mnt/mmcblk0p13/mmcblk0p1_unpartitioned.bin conv=fsync
在这条备份命令中备份的mmcblk0,根据lsblk的结果，我感觉mmcblk0是整个硬盘（115.2G），请问这里是备份整个硬盘吗。

**Comment by lgs2007m** [comment]
不是，建议你用chatgpt解析命令辅助你理解
