### ISSUE TITLE
关于京东百里的immortalWRT 固件编译

### ISSUE THREAD

**Issue by ghwrf** [lgs2007m/Actions-OpenWrt#69]
猫总，考虑更新immortalwrt的config吗，更新wifi driver,GSW驱动，mtwifi-cfg。我是新手，刚入的百里，怕自己改过去，编译出来要不得。thx

**Comment by lgs2007m** [comment]
Immortalwrt主线固件的不更新，直接在线构建就行了。
现在主要还是用hanwckf大佬的源码

**Comment by lgs2007m** [comment]
> 那我自己对比着.mtwifi-cig.config修改试试

.mtwifi-cig.config是hanwckf大佬源码用的，两者不通用，你要用主线固件直接看https://github.com/lgs2007m/Actions-OpenWrt/tree/main/JDCloud-AX6000-Baili-immortalwrt

**Comment by ghwrf** [comment]
好的，谢谢
