### ISSUE TITLE
百里的2.5G网口上行不满速如何解决？

### ISSUE THREAD

**Issue by maximaas** [lgs2007m/Actions-OpenWrt#7]
大神，我的百里是作为无线ap用，通过有线网口接到千兆交换机。
刷了[2024.05.13-1807-hanwckf-jdcloud_re-cp-03-gsw-mtwifi-docker]后，
有线插2.5G口，笔记本通过wifi实测下行110MB左右没有问题，但上行只有20-30MB。
如果有线插其他4个1000M口，上下行都是正常的，请问是哪里需要设置还是网卡的驱动问题？
谢谢回复！

**Comment by lgs2007m** [comment]
我内网测试，2.5G口eth1作为wan口或者作为br-lan的lan口，无线测速都没有问题，你自己的问题，自行解决。
hanwckf大佬仓库编译的固件是稳定没有问题的，大家都没发现的问题，就只能是自己的问题了，不要用你自己的问题来提问了
