### ISSUE TITLE
rax 3000m ttl 救砖失败

### ISSUE THREAD

**Issue by p1aintiff** [lgs2007m/Actions-OpenWrt#73]
1.设置参数
![屏幕截图 2024-11-27 181357](https://github.com/user-attachments/assets/83028ede-8786-4247-9e7d-92762fb55d08)

2. 通电刷机
![屏幕截图 2024-11-27 181424](https://github.com/user-attachments/assets/cc673c87-507e-4f75-8cbb-db1b90480e1f)

3. 日志消失，黑屏卡死
![Uploading 屏幕截图 2024-11-27 181431.png…]()

**Comment by p1aintiff** [comment]
![屏幕截图 2024-11-27 181705](https://github.com/user-attachments/assets/db3cc980-6a1d-4ad6-a410-68b25fe356cb)

**Comment by p1aintiff** [comment]
是我缺步骤了吗

**Comment by lgs2007m** [comment]
日志消失，黑屏卡死的图片出错了
