### ISSUE TITLE
升级qwrt 24后 uboot刷immortalwrt 报错

### ISSUE THREAD

**Issue by Yan-nian** [lgs2007m/Actions-OpenWrt#76]
使用的immortalwrt 下载的23.5.4和24.10.0rc sysupgrade 均报错
![CleanShot 2024-12-11 at 14 08 36@2x](https://github.com/user-attachments/assets/11d6c78b-0ecb-40de-b014-e442f954bd25)

**Comment by lgs2007m** [comment]
如果已使用我的最新uboot和gpt还报错，那就是不支持。目前我没有更新的打算
