### ISSUE TITLE
请教一下大佬，gpt.bin的分区表是如何调整的？

### ISSUE THREAD

**Issue by huxc573** [lgs2007m/Actions-OpenWrt#9]
请教一下大佬，gpt.bin的分区表是如何调整的？我有台红米ax5 京东云版（ra50）。装了openwrt挂载overlay失败，需要直接调整一下分区表大小。

**Comment by lgs2007m** [comment]
不做指导，先用[gpt_parser_to_xml.py](https://github.com/lu-1991/cdt-gpt-ipq60xx-generate/blob/master/meta-tools/scripts/gpt_parser_to_xml.py)解析你的分区表，然后参考为我以前公开的AX1800 Pro，只修改rootfs分区即可，注意总扇区数total_block要小于实际eMMC的总扇区数
https://github.com/lu-1991/cdt-gpt-ipq60xx-generate/commit/6d5aed40e57e74f0e563316028ba7d0d7369db97
